{
  parserClass="com.hand.ide.plugin.aurora.parser.AuroraParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Aurora"
  psiImplClassSuffix="Impl"
  psiPackage="com.hand.ide.plugin.aurora.psi"
  psiImplPackage="com.hand.ide.plugin.aurora.psi.impl"

  elementTypeHolderClass="com.hand.ide.plugin.aurora.psi.AuroraTypes"
  elementTypeClass="com.hand.ide.plugin.aurora.psi.AuroraElementType"
  tokenTypeClass="com.hand.ide.plugin.aurora.psi.AuroraTokenType"
}

AuroraFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY